version: '3.8'

services:
  db:
    image: mysql:8.0.30-debian
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    ports:
      - "3306:3306"
